[2025-03-22T10:56:51.084+0530] {processor.py:186} INFO - Started process (PID=32250) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:56:51.085+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T10:56:51.087+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:56:51.087+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:56:51.090+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:56:51.089+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T10:56:51.090+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:56:51.090+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T10:56:51.090+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:56:51.097+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-03-22T10:57:52.711+0530] {processor.py:186} INFO - Started process (PID=32730) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:57:52.712+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T10:57:52.714+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:57:52.714+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:57:52.717+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:57:52.717+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T10:57:52.717+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:57:52.717+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T10:57:52.717+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:57:52.724+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-03-22T10:58:50.309+0530] {processor.py:186} INFO - Started process (PID=33232) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:58:50.312+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T10:58:50.314+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:58:50.314+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:58:50.316+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:58:50.316+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T10:58:50.316+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:58:50.316+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T10:58:50.317+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:58:50.322+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-03-22T10:59:49.906+0530] {processor.py:186} INFO - Started process (PID=33605) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:59:49.907+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T10:59:49.909+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:59:49.908+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:59:49.911+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:59:49.911+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T10:59:49.911+0530] {logging_mixin.py:190} INFO - [2025-03-22T10:59:49.911+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T10:59:49.911+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T10:59:49.918+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-03-22T11:00:44.442+0530] {processor.py:186} INFO - Started process (PID=33847) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:00:44.443+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:00:44.446+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:00:44.446+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:00:44.450+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:00:44.449+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:00:44.450+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:00:44.450+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:00:44.450+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:00:44.459+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-03-22T11:01:41.166+0530] {processor.py:186} INFO - Started process (PID=35223) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:01:41.167+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:01:41.168+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:01:41.167+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:01:41.170+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:01:41.170+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:01:41.170+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:01:41.170+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:01:41.171+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:01:41.177+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:02:35.517+0530] {processor.py:186} INFO - Started process (PID=35406) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:02:35.518+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:02:35.519+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:02:35.518+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:02:35.521+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:02:35.521+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:02:35.521+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:02:35.521+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:02:35.521+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:02:35.527+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:03:29.019+0530] {processor.py:186} INFO - Started process (PID=35510) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:03:29.020+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:03:29.024+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:03:29.021+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:03:29.038+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:03:29.037+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:03:29.038+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:03:29.038+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:03:29.038+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:03:29.048+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2025-03-22T11:04:27.527+0530] {processor.py:186} INFO - Started process (PID=35617) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:04:27.527+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:04:27.528+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:04:27.528+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:04:27.531+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:04:27.530+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:04:27.531+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:04:27.531+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:04:27.531+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:04:27.539+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-03-22T11:05:19.735+0530] {processor.py:186} INFO - Started process (PID=35697) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:05:19.736+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:05:19.737+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:05:19.737+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:05:19.740+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:05:19.739+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:05:19.740+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:05:19.740+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:05:19.740+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:05:19.746+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:06:15.463+0530] {processor.py:186} INFO - Started process (PID=35768) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:06:15.464+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:06:15.464+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:06:15.464+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:06:15.467+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:06:15.466+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:06:15.467+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:06:15.467+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:06:15.467+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:06:15.474+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-03-22T11:07:08.066+0530] {processor.py:186} INFO - Started process (PID=35920) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:07:08.067+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:07:08.068+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:07:08.068+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:07:08.070+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:07:08.070+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:07:08.070+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:07:08.070+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:07:08.071+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:07:08.077+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:08:04.427+0530] {processor.py:186} INFO - Started process (PID=36051) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:08:04.427+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:08:04.428+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:08:04.428+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:08:04.431+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:08:04.431+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:08:04.431+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:08:04.431+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:08:04.431+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:08:04.438+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-03-22T11:08:54.493+0530] {processor.py:186} INFO - Started process (PID=36128) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:08:54.493+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:08:54.494+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:08:54.494+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:08:54.497+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:08:54.496+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:08:54.497+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:08:54.497+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:08:54.497+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:08:54.503+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:09:50.277+0530] {processor.py:186} INFO - Started process (PID=36279) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:09:50.278+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:09:50.280+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:09:50.280+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:09:50.283+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:09:50.282+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:09:50.283+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:09:50.283+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:09:50.283+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:09:50.290+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-03-22T11:10:41.466+0530] {processor.py:186} INFO - Started process (PID=36361) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:10:41.467+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:10:41.468+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:10:41.468+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:10:41.470+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:10:41.470+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:10:41.471+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:10:41.471+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:10:41.471+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:10:41.477+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:11:35.242+0530] {processor.py:186} INFO - Started process (PID=36523) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:11:35.244+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:11:35.245+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:11:35.244+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:11:35.248+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:11:35.247+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:11:35.248+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:11:35.248+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:11:35.248+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:11:35.259+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2025-03-22T11:12:29.804+0530] {processor.py:186} INFO - Started process (PID=36715) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:12:29.805+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:12:29.806+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:12:29.806+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:12:29.809+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:12:29.808+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:12:29.809+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:12:29.809+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:12:29.809+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:12:29.815+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-03-22T11:13:22.176+0530] {processor.py:186} INFO - Started process (PID=36789) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:13:22.177+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:13:22.178+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:13:22.178+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:13:22.180+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:13:22.180+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:13:22.180+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:13:22.180+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:13:22.181+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:13:22.187+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:14:14.577+0530] {processor.py:186} INFO - Started process (PID=36886) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:14:14.578+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:14:14.578+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:14:14.578+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:14:14.581+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:14:14.580+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:14:14.581+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:14:14.581+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:14:14.581+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:14:14.587+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:15:08.672+0530] {processor.py:186} INFO - Started process (PID=36986) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:15:08.673+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:15:08.674+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:15:08.674+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:15:08.676+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:15:08.676+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:15:08.676+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:15:08.676+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:15:08.677+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:15:08.683+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:16:00.251+0530] {processor.py:186} INFO - Started process (PID=37055) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:16:00.252+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:16:00.253+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:16:00.252+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:16:00.255+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:16:00.255+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:16:00.255+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:16:00.255+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:16:00.255+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:16:00.262+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:16:55.651+0530] {processor.py:186} INFO - Started process (PID=37222) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:16:55.652+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:16:55.652+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:16:55.652+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:16:55.655+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:16:55.655+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:16:55.655+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:16:55.655+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:16:55.656+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:16:55.663+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-03-22T11:17:48.219+0530] {processor.py:186} INFO - Started process (PID=37354) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:17:48.220+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:17:48.220+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:17:48.220+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:17:48.223+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:17:48.223+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:17:48.223+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:17:48.223+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:17:48.224+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:17:48.230+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-03-22T11:18:39.260+0530] {processor.py:186} INFO - Started process (PID=37433) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:18:39.261+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:18:39.262+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:18:39.261+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:18:39.264+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:18:39.264+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:18:39.264+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:18:39.264+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:18:39.264+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:18:39.270+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:19:30.987+0530] {processor.py:186} INFO - Started process (PID=37505) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:19:30.988+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:19:30.989+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:19:30.988+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:19:30.991+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:19:30.991+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:19:30.991+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:19:30.991+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:19:30.991+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:19:30.997+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:20:26.835+0530] {processor.py:186} INFO - Started process (PID=37596) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:20:26.836+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:20:26.837+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:20:26.836+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:20:26.839+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:20:26.839+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:20:26.839+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:20:26.839+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:20:26.839+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:20:26.845+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-03-22T11:21:19.104+0530] {processor.py:186} INFO - Started process (PID=37787) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:21:19.105+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:21:19.106+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:21:19.106+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:21:19.109+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:21:19.108+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:21:19.109+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:21:19.109+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:21:19.109+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:21:19.118+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-03-22T11:22:12.600+0530] {processor.py:186} INFO - Started process (PID=37892) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:22:12.601+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:22:12.601+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:22:12.601+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:22:12.604+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:22:12.604+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:22:12.604+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:22:12.604+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:22:12.604+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:22:12.614+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-03-22T11:23:03.036+0530] {processor.py:186} INFO - Started process (PID=38043) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:23:03.037+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:23:03.039+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:23:03.038+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:23:03.042+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:23:03.042+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:23:03.042+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:23:03.042+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:23:03.043+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:23:03.050+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-03-22T11:23:55.741+0530] {processor.py:186} INFO - Started process (PID=38143) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:23:55.742+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:23:55.743+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:23:55.743+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:23:55.746+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:23:55.746+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:23:55.746+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:23:55.746+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:23:55.747+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:23:55.754+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-03-22T11:24:50.057+0530] {processor.py:186} INFO - Started process (PID=38274) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:24:50.058+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:24:50.059+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:24:50.059+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:24:50.062+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:24:50.062+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:24:50.062+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:24:50.062+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:24:50.062+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:24:50.069+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-03-22T11:25:43.572+0530] {processor.py:186} INFO - Started process (PID=38397) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:25:43.573+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:25:43.574+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:25:43.573+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:25:43.576+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:25:43.576+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:25:43.576+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:25:43.576+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:25:43.577+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:25:43.589+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-03-22T11:26:36.651+0530] {processor.py:186} INFO - Started process (PID=38560) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:26:36.652+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:26:36.653+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:26:36.653+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:26:36.656+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:26:36.655+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:26:36.656+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:26:36.656+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:26:36.656+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:26:36.664+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-03-22T11:27:28.898+0530] {processor.py:186} INFO - Started process (PID=38672) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:27:28.899+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:27:28.902+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:27:28.900+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:27:28.908+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:27:28.907+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:27:28.908+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:27:28.908+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:27:28.908+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:27:28.917+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2025-03-22T11:28:22.701+0530] {processor.py:186} INFO - Started process (PID=38844) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:28:22.702+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:28:22.704+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:28:22.703+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:28:22.707+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:28:22.707+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:28:22.707+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:28:22.707+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:28:22.707+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:28:22.715+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-03-22T11:29:21.072+0530] {processor.py:186} INFO - Started process (PID=39050) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:29:21.073+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:29:21.074+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:29:21.073+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:29:21.077+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:29:21.076+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:29:21.077+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:29:21.077+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:29:21.077+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:29:21.086+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-03-22T11:30:18.432+0530] {processor.py:186} INFO - Started process (PID=39309) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:30:18.433+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:30:18.435+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:30:18.434+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:30:18.439+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:30:18.438+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:30:18.439+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:30:18.439+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:30:18.439+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:30:18.450+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-03-22T11:31:15.733+0530] {processor.py:186} INFO - Started process (PID=39744) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:31:15.734+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T11:31:15.735+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:31:15.734+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:31:15.737+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:31:15.737+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T11:31:15.738+0530] {logging_mixin.py:190} INFO - [2025-03-22T11:31:15.737+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T11:31:15.738+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T11:31:15.746+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-03-22T16:25:13.927+0530] {processor.py:186} INFO - Started process (PID=40963) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T16:25:13.928+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-03-22T16:25:13.929+0530] {logging_mixin.py:190} INFO - [2025-03-22T16:25:13.929+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T16:25:13.932+0530] {logging_mixin.py:190} INFO - [2025-03-22T16:25:13.932+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-03-22T16:25:13.932+0530] {logging_mixin.py:190} INFO - [2025-03-22T16:25:13.932+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-03-22T16:25:13.932+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-03-22T16:25:13.943+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
