[2025-02-26T10:44:46.956+0530] {processor.py:186} INFO - Started process (PID=100725) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:44:46.956+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:44:46.958+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:44:46.958+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:44:46.962+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:44:46.962+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:44:46.962+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:44:46.962+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:44:46.963+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:44:46.970+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-02-26T10:45:45.508+0530] {processor.py:186} INFO - Started process (PID=100875) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:45:45.508+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:45:45.510+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:45:45.510+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:45:45.512+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:45:45.512+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:45:45.513+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:45:45.513+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:45:45.513+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:45:45.520+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-02-26T10:46:40.906+0530] {processor.py:186} INFO - Started process (PID=101017) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:46:40.907+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:46:40.909+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:46:40.909+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:46:40.911+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:46:40.911+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:46:40.911+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:46:40.911+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:46:40.912+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:46:40.917+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-02-26T10:48:32.464+0530] {processor.py:186} INFO - Started process (PID=101321) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:48:32.464+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:48:32.466+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:48:32.466+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:48:32.469+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:48:32.469+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:48:32.470+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:48:32.470+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:48:32.470+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:48:32.477+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-02-26T10:49:28.996+0530] {processor.py:186} INFO - Started process (PID=101458) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:49:28.996+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:49:28.998+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:49:28.998+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:49:29.000+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:49:29.000+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:49:29.000+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:49:29.000+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:49:29.000+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:49:29.008+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-02-26T10:50:24.393+0530] {processor.py:186} INFO - Started process (PID=101554) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:50:24.394+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:50:24.395+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:50:24.395+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:50:24.398+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:50:24.397+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:50:24.398+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:50:24.398+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:50:24.398+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:50:24.404+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-02-26T10:53:06.179+0530] {processor.py:186} INFO - Started process (PID=102389) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:53:06.180+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:53:06.182+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:53:06.182+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:53:06.185+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:53:06.184+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:53:06.185+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:53:06.185+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:53:06.185+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:53:06.191+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-02-26T10:54:08.374+0530] {processor.py:186} INFO - Started process (PID=102884) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:54:08.375+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:54:08.387+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:54:08.377+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:54:08.402+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:54:08.402+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:54:08.403+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:54:08.403+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:54:08.403+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:54:08.422+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2025-02-26T10:55:21.090+0530] {processor.py:186} INFO - Started process (PID=103141) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:55:21.091+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:55:21.092+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:55:21.092+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:55:21.095+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:55:21.094+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:55:21.095+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:55:21.095+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:55:21.095+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:55:21.102+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-02-26T10:56:18.788+0530] {processor.py:186} INFO - Started process (PID=103261) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:56:18.789+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:56:18.790+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:56:18.790+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:56:18.793+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:56:18.792+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:56:18.793+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:56:18.793+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:56:18.793+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:56:18.799+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2025-02-26T10:57:14.199+0530] {processor.py:186} INFO - Started process (PID=103380) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:57:14.200+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:57:14.203+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:57:14.203+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:57:14.206+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:57:14.206+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:57:14.206+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:57:14.206+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:57:14.206+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:57:14.213+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-02-26T10:58:48.477+0530] {processor.py:186} INFO - Started process (PID=103738) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:58:48.485+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:58:48.500+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:58:48.487+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:58:48.530+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:58:48.530+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:58:48.531+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:58:48.531+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:58:48.531+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:58:48.553+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2025-02-26T10:59:45.519+0530] {processor.py:186} INFO - Started process (PID=103871) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:59:45.520+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T10:59:45.522+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:59:45.521+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:59:45.524+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:59:45.524+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T10:59:45.524+0530] {logging_mixin.py:190} INFO - [2025-02-26T10:59:45.524+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T10:59:45.524+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T10:59:45.531+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-02-26T11:00:38.385+0530] {processor.py:186} INFO - Started process (PID=103963) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:00:38.385+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:00:38.387+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:00:38.387+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:00:38.389+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:00:38.389+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:00:38.390+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:00:38.390+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:00:38.390+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:00:38.396+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-02-26T11:01:36.656+0530] {processor.py:186} INFO - Started process (PID=104069) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:01:36.657+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:01:36.659+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:01:36.658+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:01:36.661+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:01:36.661+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:01:36.661+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:01:36.661+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:01:36.661+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:01:36.667+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2025-02-26T11:02:32.302+0530] {processor.py:186} INFO - Started process (PID=104187) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:02:32.302+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:02:32.304+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:02:32.304+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:02:32.307+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:02:32.306+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:02:32.307+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:02:32.307+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:02:32.307+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:02:32.314+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2025-02-26T11:04:23.722+0530] {processor.py:186} INFO - Started process (PID=104538) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:04:23.724+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:04:23.727+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:04:23.725+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:04:23.735+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:04:23.735+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:04:23.735+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:04:23.735+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:04:23.736+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:04:23.744+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-02-26T11:05:21.147+0530] {processor.py:186} INFO - Started process (PID=104713) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:05:21.148+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:05:21.151+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:05:21.150+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:05:21.156+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:05:21.154+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:05:21.156+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:05:21.156+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:05:21.156+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:05:21.165+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2025-02-26T11:06:19.915+0530] {processor.py:186} INFO - Started process (PID=104838) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:06:19.916+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:06:19.920+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:06:19.919+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:06:19.924+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:06:19.923+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:06:19.924+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:06:19.924+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:06:19.924+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:06:19.939+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-02-26T11:07:14.031+0530] {processor.py:186} INFO - Started process (PID=104989) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:07:14.031+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:07:14.033+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:07:14.033+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:07:14.036+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:07:14.036+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:07:14.036+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:07:14.036+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:07:14.036+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:07:14.043+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2025-02-26T11:08:13.787+0530] {processor.py:186} INFO - Started process (PID=105280) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:08:13.788+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:08:13.789+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:08:13.789+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:08:13.792+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:08:13.792+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:08:13.792+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:08:13.792+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:08:13.792+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:08:13.801+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2025-02-26T11:09:10.951+0530] {processor.py:186} INFO - Started process (PID=105465) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:09:10.952+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:09:10.954+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:09:10.954+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:09:10.956+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:09:10.956+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:09:10.957+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:09:10.957+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:09:10.957+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:09:10.965+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2025-02-26T11:10:07.350+0530] {processor.py:186} INFO - Started process (PID=105578) to work on /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:10:07.351+0530] {processor.py:914} INFO - Processing file /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-02-26T11:10:07.353+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:10:07.352+0530] {dagbag.py:588} INFO - Filling up the DagBag from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:10:07.355+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:10:07.355+0530] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-02-26T11:10:07.355+0530] {logging_mixin.py:190} INFO - [2025-02-26T11:10:07.355+0530] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-02-26T11:10:07.355+0530] {processor.py:927} WARNING - No viable dags retrieved from /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-02-26T11:10:07.362+0530] {processor.py:208} INFO - Processing /home/ak265/anaconda3/envs/llm-api/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
